apiVersion: v1
kind: Service
metadata:
  name: flask-quotes-api-service
  labels:
    app: flask-quotes-api
spec:
  type: NodePort
  selector:
    app: flask-quotes-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000
